# Generated by Django 3.2.8 on 2021-10-30 16:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('last_connect', models.DateTimeField(null=True)),
                ('count_request', models.IntegerField(default=0)),
            ],
        ),
    ]
