# Generated by Django 3.2.8 on 2021-10-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communicator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='info',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='last_connect',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
