# Generated by Django 3.2.8 on 2021-10-30 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Communicator', '0002_auto_20211030_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to=settings.AUTH_USER_MODEL),
        ),
    ]
