# Generated by Django 3.2.8 on 2021-10-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communicator', '0003_terminal_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='metric',
            field=models.IntegerField(default=0),
        ),
    ]
