# Generated by Django 3.2.8 on 2021-11-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communicator', '0004_terminal_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='count_request_error',
            field=models.IntegerField(default=0),
        ),
    ]
