# Generated by Django 3.2.8 on 2021-11-03 12:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Communicator', '0005_terminal_count_request_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_create', models.DateTimeField(default=datetime.datetime(2021, 11, 3, 15, 33, 13, 869521))),
                ('event_type', models.IntegerField(choices=[(0, 'Get')], default=0)),
                ('request', models.CharField(max_length=100)),
                ('data_completed', models.DateTimeField(blank=True)),
                ('status_completed', models.BooleanField(blank=True, null=True)),
                ('response', models.TextField()),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Communicator.terminal')),
            ],
        ),
    ]
