# Generated by Django 3.2.8 on 2021-11-03 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communicator', '0006_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='status_completed',
            new_name='success',
        ),
        migrations.AlterField(
            model_name='event',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 18, 23, 38, 600707)),
        ),
    ]
