# Generated by Django 3.2.8 on 2021-11-03 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communicator', '0007_auto_20211103_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 18, 24, 47, 828177)),
        ),
        migrations.AlterField(
            model_name='event',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
