# Generated by Django 3.2.8 on 2021-11-03 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communicator', '0009_auto_20211103_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 18, 38, 24, 141467)),
        ),
    ]
