# Generated by Django 3.2.8 on 2021-11-03 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communicator', '0011_alter_event_data_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 22, 23, 55, 63714)),
        ),
    ]
