# Generated by Django 3.2.8 on 2021-11-20 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communicator', '0014_auto_20211116_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 20, 17, 40, 8, 154802)),
        ),
        migrations.AlterField(
            model_name='event',
            name='request',
            field=models.CharField(max_length=300),
        ),
    ]
