kind: pipeline
type: ssh
name: python.Client

platform:
  os: linux
  arch: amd64

server:
  host: 176.107.130.186
  user: root
  password:
    from_secret: ssh_password

clone:
  skip_verify: true

steps:
- name: build
  commands:
  - docker build -t terminal_python_client . -f Clients/Python.Client/Dockerfile ;

- name: delete old containers
  failure: ignore
  commands:
  - docker stop terminal_python_client;
  - docker rm terminal_python_client;

- name: publish
  environment:
    CLIENT_API_URL:
      from_secret: client_api_url
  commands:
  - docker run -d --restart=no -m=350m --memory-swap=350m --cpus=".5" --pids-limit=200 -e="API_URL":${CLIENT_API_URL} --name terminal_python_client terminal_python_client;
