kind: pipeline
type: exec
name: python.Client

platform:
  os: linux
  arch: amd64

clone:
  skip_verify: true
  
steps:
- name: build
  commands:
  - docker build -t terminal_python_client . -f Cleint\Python.Client\Dockerfile ;

- name: delete old containers
  failure: ignore
  commands:
  - docker stop terminal_python_client;
  - docker rm terminal_python_client;

- name: publish
  commands:
  - docker run -d --restart=no -m=350m --memory-swap=350m --cpus=".5" --pids-limit=200 --name terminal_python_client terminal_python_client;

- name: notification
  pull: true
  image: appleboy/drone-telegram
  settings:
    token:
        from_secret: bot_token
    to: -1001419585850

---
kind: pipeline
type: docker
name: plugin_local

clone:
  skip_verify: true

platform:
  os: linux
  arch: amd64

steps:
- name: notification
  pull: true
  image: appleboy/drone-telegram
  settings:
    token:
        from_secret: bot_token
    to: -1001419585850