kind: pipeline
type: exec
name: Terminal.Client.Python.

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
  - docker build -t terminal_python_client . -f Clients/Python.Client/Dockerfile;

- name: delete old containers
  failure: ignore
  commands:
  - docker stop terminal_python_client;
  - docker rm terminal_python_client;

- name: publish
  environment:
    CLIENT_API_TOKEN:
      from_secret: CLIENT_API_TOKEN
  commands:
  - docker run -d --restart=no -m=350m --memory-swap=350m --cpus=".5" --pids-limit=200 -e=API_URL='http://cgbot.ru:81/' -e=NAME='PL.Aruba.Python' -e=API_KEY=$CLIENT_API_TOKEN --name terminal_python_client terminal_python_client;

---

kind: pipeline
type: exec
name: Terminal.Communicator

platform:
  os: linux
  arch: amd64

steps:
- name: build and run
  commands:
    - docker-compose -f docker-compose.prod.yml up -d --build

