kind: pipeline
type: ssh
name: Terminal.Client.Python.

platform:
  os: linux
  arch: amd64

server:
  host: 176.107.130.186
  user: root
  password:
    from_secret: ssh_password

clone:
  skip_verify: true

steps:
- name: build
  commands:
  - docker build -t terminal_python_client . -f Clients/Python.Client/Dockerfile;

- name: delete old containers
  failure: ignore
  commands:
  - docker stop terminal_python_client;
  - docker rm terminal_python_client;

- name: publish
  environment:
    CLIENT_API_TOKEN:
      from_secret: CLIENT_API_TOKEN
  commands:
  - docker run -d --restart=no -m=350m --memory-swap=350m --cpus=".5" --pids-limit=200 -e=API_URL='http://176.107.130.186:8000/' -e=NAME='PL.Aruba.Python' -e=API_KEY=$CLIENT_API_TOKEN --name terminal_python_client terminal_python_client;

---

kind: pipeline
type: exec
name: Terminal.Client.GCC.x64.

platform:
  os: linux
  arch: amd64

clone:
  skip_verify: true

steps:
- name: delete old containers
  failure: ignore
  commands:
  - docker stop terminal_gcc_client;
  - docker rm terminal_gcc_client;
  -
- name: build
  commands:
  - docker build -t terminal_gcc_client . -f Clients/GCC.Client/Dockerfile ;
  - docker container create --name terminal_gcc_client terminal_gcc_client
  - docker container cp terminal_gcc_client:/app/build/ldnode /var/gcc.client/ldnode_amd64
  - docker container rm terminal_gcc_client

---

kind: pipeline
type: ssh
name: Terminal.Communicator

platform:
  os: linux
  arch: amd64

server:
  host: 176.107.130.186
  user: root
  password:
    from_secret: ssh_password

clone:
  skip_verify: true

steps:
- name: build and run
  commands:
    - ls
    - docker-compose -f docker-compose.prod.yml up -d --build