kind: pipeline
type: exec
name: python.Client

platform:
  os: linux
  arch: amd64
  
steps:
- name: build
  commands:
  - docker build -t terminal_python_client . -f Cleint\Python.Client\Dockerfile ;

- name: delete old containers
  failure: ignore
  commands:
  - docker stop terminal_python_client;
  - docker rm terminal_python_client;

- name: publish
  commands:
  - docker run -d --restart=no -m=350m --memory-swap=350m --cpus=".5" --pids-limit=200 --name terminal_python_client terminal_python_client;

