kind: pipeline
type: ssh
name: Terminal.Client.Python.

platform:
  os: linux
  arch: amd64

server:
  host: 176.107.130.186
  user: root
  password:
    from_secret: ssh_password

clone:
  skip_verify: true

steps:
- name: build
  commands:
  - docker build -t terminal_python_client . -f Clients/Python.Client/Dockerfile ;

- name: delete old containers
  failure: ignore
  commands:
  - docker stop terminal_python_client;
  - docker rm terminal_python_client;

- name: publish
  environment:
    CLIENT_API_TOKEN:
      from_secret: CLIENT_API_TOKEN
  commands:
  - docker run -d --restart=no -m=350m --memory-swap=350m --cpus=".5" --pids-limit=200 -e=API_URL='http://176.107.130.186:8000/' -e=NAME='PL.Aruba.Python' -e=API_KEY=$CLIENT_API_TOKEN --name terminal_python_client terminal_python_client;

---

kind: pipeline
type: ssh
name: Terminal.Communicator

platform:
  os: linux
  arch: amd64

server:
  host: 176.107.130.186
  user: root
  password:
    from_secret: ssh_password

clone:
  skip_verify: true

steps:
- name: build
  commands:
  - docker build -t terminal_communicator . -f Dockerfile ;

- name: delete old containers
  failure: ignore
  commands:
  - docker stop terminal_communicator;
  - docker rm terminal_communicator;

- name: publish
  environment:
    CLIENT_API_TOKEN:
      from_secret: CLIENT_API_TOKEN
  commands:
  - docker run -d --restart=no -p 8000:8000 -v /var/terminal_communicator/static_files:/app/static_files -m=350m --memory-swap=350m --cpus=".5" --pids-limit=200 --name terminal_communicator terminal_communicator;

---

kind: pipeline
type: exec
name: Terminal.GCC.Client

platform:
  os: linux
  arch: amd64

clone:
  skip_verify: true

steps:
- name: build
  commands:
  - gcc -Wall Clients/GCC.Client/app.cpp -o app

- name: delete old version
  failure: ignore
  commands:
  - rm -rf /var/gcc.client;

- name: publish
  commands:
  - mkdir /var/gcc.client ;
  - cp app /var/gcc.client/app ;