version: "3.7"

services:
  web:
    container_name: terminal_communicator
    build:
      context: .
      dockerfile: Dockerfile.prod
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn -b 0.0.0.0:8000 --workers=2 --threads=4 --worker-class=gthread TerminalCommunicator.wsgi:application
    volumes:
      - staticfiles:/app/staticfiles
    ports:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql_tc/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - staticfiles:/staticfiles
    ports:
      - 81:80
    depends_on:
      - web

volumes:
  postgres_data:
  staticfiles: