###
GET http://localhost:8000/api/ping/
Accept: */*
Cache-Control: no-cache
Authorization: Token {{token}}

###

POST http://localhost:8000/api/ping/
Authorization: Token {{token}}
Accept: application/json
Content-Type: application/json

{
  "name":
  "Terminal1"
}

###
GET http://localhost:8000/api/token?name=UserTest
Accept: application/json
Authorization: Token {{token}}


