POST http://localhost:8000/api/event/
Authorization: Token {{token}}
Accept: application/json
Content-Type: application/json

{
  "id": "ef2900ea-547c-4c9a-82ef-87a489dee3f9",
  "response": "Test222",
  "success" : true
}


###
GET http://localhost:8000/api/event?name=Terminal1
Accept: application/json
Authorization: Token {{token}}

###
GET http://localhost:8000/api/ping/
Accept: */*
Cache-Control: no-cache
Authorization: Token {{token}}

###

POST http://localhost:8000/api/ping/
Authorization: Token {{token}}
Accept: application/json
Content-Type: application/json

{
  "name":
  "Terminal1"
}

###
GET http://localhost:8000/api/token?name=UserTest
Accept: application/json
Authorization: Token {{token}}


